using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Simple.Objects;

#nullable enable

namespace DemoApp.Objects
{
    #region |   Code Generated by Simple.Objects Code Generator   |

    partial class UserGraphPolicy
    {
        #region |   Protected Members   |

        protected long previousId, oldPreviousId;
        protected long userId, oldUserId;
        protected long graphElementId, oldGraphElementId;
        protected int graphKey, oldGraphKey;
        protected UserPolicyRights policyRights, oldPolicyRights;
        protected int orderIndex, oldOrderIndex;

        #endregion |   Protected Members   |

        #region |   Private Static Members   |

        private static Func<UserGraphPolicy, object?>[] GetFieldValueMethods;
        private static Func<UserGraphPolicy, object?>[] GetOldFieldValueMethods;
        private static Action<UserGraphPolicy, object>[] SetFieldValueMethods;
        private static Action<UserGraphPolicy, object>[] SetOldFieldValueMethods;

        #endregion |   Private Static Members   |

        #region |   Static Methods Initialization   |

        static UserGraphPolicy()
        {
            int maxIndex = UserGraphPolicyModel.PropertyModel.GetCollection().GetMaxIndex();

            GetFieldValueMethods = new Func<UserGraphPolicy, object?>[maxIndex + 1];
            GetFieldValueMethods[UserGraphPolicyModel.PropertyModel.Id.PropertyIndex]             = (item) => item.id;
            GetFieldValueMethods[UserGraphPolicyModel.PropertyModel.PreviousId.PropertyIndex]     = (item) => item.previousId;
            GetFieldValueMethods[UserGraphPolicyModel.PropertyModel.UserId.PropertyIndex]         = (item) => item.userId;
            GetFieldValueMethods[UserGraphPolicyModel.PropertyModel.GraphElementId.PropertyIndex] = (item) => item.graphElementId;
            GetFieldValueMethods[UserGraphPolicyModel.PropertyModel.GraphKey.PropertyIndex]       = (item) => item.graphKey;
            GetFieldValueMethods[UserGraphPolicyModel.PropertyModel.PolicyRights.PropertyIndex]   = (item) => item.policyRights;
            GetFieldValueMethods[UserGraphPolicyModel.PropertyModel.OrderIndex.PropertyIndex]     = (item) => item.orderIndex;

            GetOldFieldValueMethods = new Func<UserGraphPolicy, object?>[maxIndex + 1];
            GetOldFieldValueMethods[UserGraphPolicyModel.PropertyModel.Id.PropertyIndex]             = (item) => item.oldId;
            GetOldFieldValueMethods[UserGraphPolicyModel.PropertyModel.PreviousId.PropertyIndex]     = (item) => item.oldPreviousId;
            GetOldFieldValueMethods[UserGraphPolicyModel.PropertyModel.UserId.PropertyIndex]         = (item) => item.oldUserId;
            GetOldFieldValueMethods[UserGraphPolicyModel.PropertyModel.GraphElementId.PropertyIndex] = (item) => item.oldGraphElementId;
            GetOldFieldValueMethods[UserGraphPolicyModel.PropertyModel.GraphKey.PropertyIndex]       = (item) => item.oldGraphKey;
            GetOldFieldValueMethods[UserGraphPolicyModel.PropertyModel.PolicyRights.PropertyIndex]   = (item) => item.oldPolicyRights;
            GetOldFieldValueMethods[UserGraphPolicyModel.PropertyModel.OrderIndex.PropertyIndex]     = (item) => item.oldOrderIndex;

            SetFieldValueMethods = new Action<UserGraphPolicy, object>[maxIndex + 1];
            SetFieldValueMethods[UserGraphPolicyModel.PropertyModel.Id.PropertyIndex]             = (item, value) => item.id = (long)value;
            SetFieldValueMethods[UserGraphPolicyModel.PropertyModel.PreviousId.PropertyIndex]     = (item, value) => item.previousId = (long)value;
            SetFieldValueMethods[UserGraphPolicyModel.PropertyModel.UserId.PropertyIndex]         = (item, value) => item.userId = (long)value;
            SetFieldValueMethods[UserGraphPolicyModel.PropertyModel.GraphElementId.PropertyIndex] = (item, value) => item.graphElementId = (long)value;
            SetFieldValueMethods[UserGraphPolicyModel.PropertyModel.GraphKey.PropertyIndex]       = (item, value) => item.graphKey = (int)value;
            SetFieldValueMethods[UserGraphPolicyModel.PropertyModel.PolicyRights.PropertyIndex]   = (item, value) => item.policyRights = (UserPolicyRights)value;
            SetFieldValueMethods[UserGraphPolicyModel.PropertyModel.OrderIndex.PropertyIndex]     = (item, value) => item.orderIndex = (int)value;

            SetOldFieldValueMethods = new Action<UserGraphPolicy, object>[maxIndex + 1];
            SetOldFieldValueMethods[UserGraphPolicyModel.PropertyModel.Id.PropertyIndex]             = (item, value) => item.oldId = (long)value;
            SetOldFieldValueMethods[UserGraphPolicyModel.PropertyModel.PreviousId.PropertyIndex]     = (item, value) => item.oldPreviousId = (long)value;
            SetOldFieldValueMethods[UserGraphPolicyModel.PropertyModel.UserId.PropertyIndex]         = (item, value) => item.oldUserId = (long)value;
            SetOldFieldValueMethods[UserGraphPolicyModel.PropertyModel.GraphElementId.PropertyIndex] = (item, value) => item.oldGraphElementId = (long)value;
            SetOldFieldValueMethods[UserGraphPolicyModel.PropertyModel.GraphKey.PropertyIndex]       = (item, value) => item.oldGraphKey = (int)value;
            SetOldFieldValueMethods[UserGraphPolicyModel.PropertyModel.PolicyRights.PropertyIndex]   = (item, value) => item.oldPolicyRights = (UserPolicyRights)value;
            SetOldFieldValueMethods[UserGraphPolicyModel.PropertyModel.OrderIndex.PropertyIndex]     = (item, value) => item.oldOrderIndex = (int)value;
        }

        #endregion |   Static Methods Initialization   |

        #region |   Properties by Object Property Model   |

        /// <summary>
        /// Gets or sets PreviousId
        /// </summary>
        public long PreviousId
        {
            get { return this.previousId; }
            protected internal set { this.SetPropertyValue(UserGraphPolicyModel.PropertyModel.PreviousId, value); }
		}

        /// <summary>
        /// Gets or sets UserId
        /// </summary>
        public long UserId
        {
            get { return this.userId; }
            set { this.SetPropertyValue(UserGraphPolicyModel.PropertyModel.UserId, value); }
		}

        /// <summary>
        /// Gets or sets GraphElementId
        /// </summary>
        public long GraphElementId
        {
            get { return this.graphElementId; }
            set { this.SetPropertyValue(UserGraphPolicyModel.PropertyModel.GraphElementId, value); }
		}

        /// <summary>
        /// Gets or sets GraphKey
        /// </summary>
        public int GraphKey
        {
            get { return this.graphKey; }
            set { this.SetPropertyValue(UserGraphPolicyModel.PropertyModel.GraphKey, value); }
		}

        /// <summary>
        /// Gets or sets PolicyRights
        /// </summary>
        public UserPolicyRights PolicyRights
        {
            get { return this.policyRights; }
            set { this.SetPropertyValue(UserGraphPolicyModel.PropertyModel.PolicyRights, value); }
		}

        /// <summary>
        /// Gets or sets OrderIndex
        /// </summary>
        public int OrderIndex
        {
            get { return this.orderIndex; }
            set { this.SetPropertyValue(UserGraphPolicyModel.PropertyModel.OrderIndex, value); }
		}

        #endregion |   Properties by Object Property Model   |

        #region |   One-To-Many Relation Properties   |

        /// <summary>
        /// Gets or sets one-to-many relation primary User object.
        /// </summary>
        public User User
        {
            get { return this.GetOneToManyPrimaryObject<User>(RelationPolicyModel.OneToManyUserGraphPolicyToUser)!; }
            set { this.SetOneToManyPrimaryObject(value, RelationPolicyModel.OneToManyUserGraphPolicyToUser); }
        }

        /// <summary>
        /// Gets one-to-many relation foreign GraphElements collection.
        /// </summary>
        public override SimpleObjectCollection<GraphElement> GraphElements
        {
            get { return this.GetOneToManyForeignObjectCollection<GraphElement>(RelationPolicyModelBase.OneToManyGraphElementToSimpleObject); }
        }

        #endregion |   One-To-Many Relation Properties   |

        #region |   Public Overriden Methods   |

        /// <summary>
        /// Gets the UserGraphPolicyModel definition instance.
        /// </summary>
        public override ISimpleObjectModel GetModel()
        {
            return UserGraphPolicyModel.Instance; 
        }

        /// <summary>
        /// Gets the one-to-many collection based on relation key. If no one-to-many relation specified in relation model for this object, the base class method is called.
        /// </summary>
        /// <param name="relationKey">The one-to-many relation key</param>
        /// <returns>The <see cref="SimpleObjectCollection?"/> result.</returns>
        public override SimpleObjectCollection? GetOneToManyForeignObjectCollection(int relationKey)
        {
            if (relationKey == RelationPolicyModelBase.OneToManyGraphElementToSimpleObject.RelationKey)
                return this.GraphElements;

            return base.GetOneToManyForeignObjectCollection(relationKey);
        }

        #endregion |   Public Overriden Methods   |

        #region |   Protected Abstract Overriden Methods  |

        /// <summary>
        /// Gets field property value by property index.
        /// </summary>
        protected override object? GetFieldValue(int propertyIndex)
        {
            return GetFieldValueMethods[propertyIndex](this);
        }

        /// <summary>
        /// Gets field old property value by property index.
        /// </summary>
        protected override object? GetOldFieldValue(int propertyIndex)
        {
            return GetOldFieldValueMethods[propertyIndex](this);
        }

        /// <summary>
        /// Sets field property value by property index.
        /// </summary>
        protected override void SetFieldValue(int propertyIndex, object value)
        {
            SetFieldValueMethods[propertyIndex](this, value);
        }

        /// <summary>
        /// Sets field old property value by property index.
        /// </summary>
        protected override void SetOldFieldValue(int propertyIndex, object value)
        {
            SetOldFieldValueMethods[propertyIndex](this, value);
        }

        #endregion |   Protected Abstract Overriden Methods  |
    }

    #endregion |   Code Generated by Simple.Objects Code Generator   |
}
