using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Simple.Objects;

#nullable enable

namespace DemoApp.Objects
{
    #region |   Code Generated by Simple.Objects Code Generator   |

    partial class UserGroup
    {
        #region |   Protected Members   |

        protected string name = String.Empty, oldName = String.Empty;
        protected string description = String.Empty, oldDescription = String.Empty;
        protected bool disabled, oldDisabled;
        protected int codePage, oldCodePage;
        protected int defaultGraphPolicy, oldDefaultGraphPolicy;
        protected int defaultObjectPolicy, oldDefaultObjectPolicy;

        #endregion |   Protected Members   |

        #region |   Private Static Members   |

        private static Func<UserGroup, object?>[] GetFieldValueMethods;
        private static Func<UserGroup, object?>[] GetOldFieldValueMethods;
        private static Action<UserGroup, object>[] SetFieldValueMethods;
        private static Action<UserGroup, object>[] SetOldFieldValueMethods;

        #endregion |   Private Static Members   |

        #region |   Static Methods Initialization   |

        static UserGroup()
        {
            int maxIndex = UserGroupModel.PropertyModel.GetCollection().GetMaxIndex();

            GetFieldValueMethods = new Func<UserGroup, object?>[maxIndex + 1];
            GetFieldValueMethods[UserGroupModel.PropertyModel.Id.PropertyIndex]                  = (item) => item.id;
            GetFieldValueMethods[UserGroupModel.PropertyModel.PreviousId.PropertyIndex]          = (item) => item.previousId;
            GetFieldValueMethods[UserGroupModel.PropertyModel.Name.PropertyIndex]                = (item) => item.name;
            GetFieldValueMethods[UserGroupModel.PropertyModel.Description.PropertyIndex]         = (item) => item.description;
            GetFieldValueMethods[UserGroupModel.PropertyModel.Disabled.PropertyIndex]            = (item) => item.disabled;
            GetFieldValueMethods[UserGroupModel.PropertyModel.CodePage.PropertyIndex]            = (item) => item.codePage;
            GetFieldValueMethods[UserGroupModel.PropertyModel.DefaultGraphPolicy.PropertyIndex]  = (item) => item.defaultGraphPolicy;
            GetFieldValueMethods[UserGroupModel.PropertyModel.DefaultObjectPolicy.PropertyIndex] = (item) => item.defaultObjectPolicy;
            GetFieldValueMethods[UserGroupModel.PropertyModel.OrderIndex.PropertyIndex]          = (item) => item.orderIndex;

            GetOldFieldValueMethods = new Func<UserGroup, object?>[maxIndex + 1];
            GetOldFieldValueMethods[UserGroupModel.PropertyModel.Id.PropertyIndex]                  = (item) => item.oldId;
            GetOldFieldValueMethods[UserGroupModel.PropertyModel.PreviousId.PropertyIndex]          = (item) => item.oldPreviousId;
            GetOldFieldValueMethods[UserGroupModel.PropertyModel.Name.PropertyIndex]                = (item) => item.oldName;
            GetOldFieldValueMethods[UserGroupModel.PropertyModel.Description.PropertyIndex]         = (item) => item.oldDescription;
            GetOldFieldValueMethods[UserGroupModel.PropertyModel.Disabled.PropertyIndex]            = (item) => item.oldDisabled;
            GetOldFieldValueMethods[UserGroupModel.PropertyModel.CodePage.PropertyIndex]            = (item) => item.oldCodePage;
            GetOldFieldValueMethods[UserGroupModel.PropertyModel.DefaultGraphPolicy.PropertyIndex]  = (item) => item.oldDefaultGraphPolicy;
            GetOldFieldValueMethods[UserGroupModel.PropertyModel.DefaultObjectPolicy.PropertyIndex] = (item) => item.oldDefaultObjectPolicy;
            GetOldFieldValueMethods[UserGroupModel.PropertyModel.OrderIndex.PropertyIndex]          = (item) => item.oldOrderIndex;

            SetFieldValueMethods = new Action<UserGroup, object>[maxIndex + 1];
            SetFieldValueMethods[UserGroupModel.PropertyModel.Id.PropertyIndex]                  = (item, value) => item.id = (long)value;
            SetFieldValueMethods[UserGroupModel.PropertyModel.PreviousId.PropertyIndex]          = (item, value) => item.previousId = (long)value;
            SetFieldValueMethods[UserGroupModel.PropertyModel.Name.PropertyIndex]                = (item, value) => item.name = (string)value;
            SetFieldValueMethods[UserGroupModel.PropertyModel.Description.PropertyIndex]         = (item, value) => item.description = (string)value;
            SetFieldValueMethods[UserGroupModel.PropertyModel.Disabled.PropertyIndex]            = (item, value) => item.disabled = (bool)value;
            SetFieldValueMethods[UserGroupModel.PropertyModel.CodePage.PropertyIndex]            = (item, value) => item.codePage = (int)value;
            SetFieldValueMethods[UserGroupModel.PropertyModel.DefaultGraphPolicy.PropertyIndex]  = (item, value) => item.defaultGraphPolicy = (int)value;
            SetFieldValueMethods[UserGroupModel.PropertyModel.DefaultObjectPolicy.PropertyIndex] = (item, value) => item.defaultObjectPolicy = (int)value;
            SetFieldValueMethods[UserGroupModel.PropertyModel.OrderIndex.PropertyIndex]          = (item, value) => item.orderIndex = (int)value;

            SetOldFieldValueMethods = new Action<UserGroup, object>[maxIndex + 1];
            SetOldFieldValueMethods[UserGroupModel.PropertyModel.Id.PropertyIndex]                  = (item, value) => item.oldId = (long)value;
            SetOldFieldValueMethods[UserGroupModel.PropertyModel.PreviousId.PropertyIndex]          = (item, value) => item.oldPreviousId = (long)value;
            SetOldFieldValueMethods[UserGroupModel.PropertyModel.Name.PropertyIndex]                = (item, value) => item.oldName = (string)value;
            SetOldFieldValueMethods[UserGroupModel.PropertyModel.Description.PropertyIndex]         = (item, value) => item.oldDescription = (string)value;
            SetOldFieldValueMethods[UserGroupModel.PropertyModel.Disabled.PropertyIndex]            = (item, value) => item.oldDisabled = (bool)value;
            SetOldFieldValueMethods[UserGroupModel.PropertyModel.CodePage.PropertyIndex]            = (item, value) => item.oldCodePage = (int)value;
            SetOldFieldValueMethods[UserGroupModel.PropertyModel.DefaultGraphPolicy.PropertyIndex]  = (item, value) => item.oldDefaultGraphPolicy = (int)value;
            SetOldFieldValueMethods[UserGroupModel.PropertyModel.DefaultObjectPolicy.PropertyIndex] = (item, value) => item.oldDefaultObjectPolicy = (int)value;
            SetOldFieldValueMethods[UserGroupModel.PropertyModel.OrderIndex.PropertyIndex]          = (item, value) => item.oldOrderIndex = (int)value;
        }

        #endregion |   Static Methods Initialization   |

        #region |   Properties by Object Property Model   |

        /// <summary>
        /// Gets or sets Name
        /// </summary>
        public string Name
        {
            get { return this.name; }
            set { this.SetPropertyValue(UserGroupModel.PropertyModel.Name, value); }
		}

        /// <summary>
        /// Gets or sets Description
        /// </summary>
        public string Description
        {
            get { return this.description; }
            set { this.SetPropertyValue(UserGroupModel.PropertyModel.Description, value); }
		}

        /// <summary>
        /// Gets or sets Disabled
        /// </summary>
        public bool Disabled
        {
            get { return this.disabled; }
            set { this.SetPropertyValue(UserGroupModel.PropertyModel.Disabled, value); }
		}

        /// <summary>
        /// Gets or sets CodePage
        /// </summary>
        public int CodePage
        {
            get { return this.codePage; }
            set { this.SetPropertyValue(UserGroupModel.PropertyModel.CodePage, value); }
		}

        /// <summary>
        /// Gets or sets DefaultGraphPolicy
        /// </summary>
        public int DefaultGraphPolicy
        {
            get { return this.defaultGraphPolicy; }
            set { this.SetPropertyValue(UserGroupModel.PropertyModel.DefaultGraphPolicy, value); }
		}

        /// <summary>
        /// Gets or sets DefaultObjectPolicy
        /// </summary>
        public int DefaultObjectPolicy
        {
            get { return this.defaultObjectPolicy; }
            set { this.SetPropertyValue(UserGroupModel.PropertyModel.DefaultObjectPolicy, value); }
		}

        #endregion |   Properties by Object Property Model   |

        #region |   One-To-Many Relation Properties   |

        /// <summary>
        /// Gets one-to-many relation foreign GraphElements collection.
        /// </summary>
        public override SimpleObjectCollection<GraphElement> GraphElements
        {
            get { return this.GetOneToManyForeignObjectCollection<GraphElement>(RelationPolicyModelBase.OneToManyGraphElementToSimpleObject); }
        }

        #endregion |   One-To-Many Relation Properties   |

        #region |   Many-To-Many Relation Properties   |

        /// <summary>
        /// Gets membership Users collection.
        /// </summary>
        public SimpleObjectCollection<User> Users
        {
            get { return this.GetGroupMemberCollection<User>(RelationPolicyModel.ManyToManyUserToUserGroup); }
        }

        #endregion |   Many-To-Many Relation Properties   |

        #region |   Public Overriden Methods   |

        /// <summary>
        /// Gets the UserGroupModel definition instance.
        /// </summary>
        public override ISimpleObjectModel GetModel()
        {
            return UserGroupModel.Instance; 
        }

        /// <summary>
        /// Gets the one-to-many collection based on relation key. If no one-to-many relation specified in relation model for this object, the base class method is called.
        /// </summary>
        /// <param name="relationKey">The one-to-many relation key</param>
        /// <returns>The <see cref="SimpleObjectCollection?"/> result.</returns>
        public override SimpleObjectCollection? GetOneToManyForeignObjectCollection(int relationKey)
        {
            //if (relationKey == RelationPolicyModelBase.OneToManyGraphElementToSimpleObject.RelationKey)
            //{
            //    return this.GraphElements;
            //}
            //else if (relationKey == RelationPolicyModel.OneToManyUserPolicyToUserObject.RelationKey)
            //{
            //    return null;
            //}

            return base.GetOneToManyForeignObjectCollection(relationKey);
        }

        /// <summary>
        /// Gets the group member collection based on relation key. If no many-to-many relation specified in relation model for this object, the base class method is called.
        /// </summary>
        /// <param name="relationKey">The many-to-many relation key</param>
        /// <returns>The <see cref="SimpleObjectCollection?"/> result.</returns>
        public override SimpleObjectCollection? GetGroupMemberCollection(int relationKey)
        {
            if (relationKey == RelationPolicyModel.ManyToManyUserToUserGroup.RelationKey)
                return this.Users;

            return base.GetGroupMemberCollection(relationKey);
        }

        #endregion |   Public Overriden Methods   |

        #region |   Protected Abstract Overriden Methods  |

        /// <summary>
        /// Gets field property value by property index.
        /// </summary>
        protected override object? GetFieldValue(int propertyIndex)
        {
            return GetFieldValueMethods[propertyIndex](this);
        }

        /// <summary>
        /// Gets field old property value by property index.
        /// </summary>
        protected override object? GetOldFieldValue(int propertyIndex)
        {
            return GetOldFieldValueMethods[propertyIndex](this);
        }

        /// <summary>
        /// Sets field property value by property index.
        /// </summary>
        protected override void SetFieldValue(int propertyIndex, object value)
        {
            SetFieldValueMethods[propertyIndex](this, value);
        }

        /// <summary>
        /// Sets field old property value by property index.
        /// </summary>
        protected override void SetOldFieldValue(int propertyIndex, object value)
        {
            SetOldFieldValueMethods[propertyIndex](this, value);
        }

        #endregion |   Protected Abstract Overriden Methods  |
    }

    #endregion |   Code Generated by Simple.Objects Code Generator   |
}
