using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Simple.Objects;

#nullable enable

namespace DemoApp.Objects
{
    #region |   Code Generated by Simple.Objects Code Generator   |

    partial class UserObject
    {
        #region |   One-To-Many Relation Properties   |

        ///// <summary>
        ///// Gets one-to-many relation foreign UserPolicies collection.
        ///// </summary>
        //public SimpleObjectCollection<UserPolicy> UserPolicies
        //{
        //    get { return this.GetOneToManyForeignObjectCollection<UserPolicy>(RelationPolicyModel.OneToManyUserPolicyToUserObject); }
        //}

        #endregion |   One-To-Many Relation Properties   |
    }

    #endregion |   Code Generated by Simple.Objects Code Generator   |
}
