using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Simple.Objects;

#nullable enable

namespace DemoApp.Objects
{
    #region |   Code Generated by Simple.Objects Code Generator   |

    partial class UserObjectPolicy
    {
        #region |   Protected Members   |

        protected long userId, oldUserId;
        protected int objectTableId, oldObjectTableId;
        protected long objectId, oldObjectId;
        protected UserPolicyRights policyRights, oldPolicyRights;

        #endregion |   Protected Members   |

        #region |   Private Static Members   |

        private static Func<UserObjectPolicy, object?>[] GetFieldValueMethods;
        private static Func<UserObjectPolicy, object?>[] GetOldFieldValueMethods;
        private static Action<UserObjectPolicy, object>[] SetFieldValueMethods;
        private static Action<UserObjectPolicy, object>[] SetOldFieldValueMethods;

        #endregion |   Private Static Members   |

        #region |   Static Methods Initialization   |

        static UserObjectPolicy()
        {
            int maxIndex = UserObjectPolicyModel.PropertyModel.GetCollection().GetMaxIndex();

            GetFieldValueMethods = new Func<UserObjectPolicy, object?>[maxIndex + 1];
            GetFieldValueMethods[UserObjectPolicyModel.PropertyModel.Id.PropertyIndex]            = (item) => item.id;
            GetFieldValueMethods[UserObjectPolicyModel.PropertyModel.PreviousId.PropertyIndex]    = (item) => item.previousId;
            GetFieldValueMethods[UserObjectPolicyModel.PropertyModel.UserId.PropertyIndex]        = (item) => item.userId;
            GetFieldValueMethods[UserObjectPolicyModel.PropertyModel.ObjectTableId.PropertyIndex] = (item) => item.objectTableId;
            GetFieldValueMethods[UserObjectPolicyModel.PropertyModel.ObjectId.PropertyIndex]      = (item) => item.objectId;
            GetFieldValueMethods[UserObjectPolicyModel.PropertyModel.PolicyRights.PropertyIndex]  = (item) => item.policyRights;
            GetFieldValueMethods[UserObjectPolicyModel.PropertyModel.OrderIndex.PropertyIndex]    = (item) => item.orderIndex;

            GetOldFieldValueMethods = new Func<UserObjectPolicy, object?>[maxIndex + 1];
            GetOldFieldValueMethods[UserObjectPolicyModel.PropertyModel.Id.PropertyIndex]            = (item) => item.oldId;
            GetOldFieldValueMethods[UserObjectPolicyModel.PropertyModel.PreviousId.PropertyIndex]    = (item) => item.oldPreviousId;
            GetOldFieldValueMethods[UserObjectPolicyModel.PropertyModel.UserId.PropertyIndex]        = (item) => item.oldUserId;
            GetOldFieldValueMethods[UserObjectPolicyModel.PropertyModel.ObjectTableId.PropertyIndex] = (item) => item.oldObjectTableId;
            GetOldFieldValueMethods[UserObjectPolicyModel.PropertyModel.ObjectId.PropertyIndex]      = (item) => item.oldObjectId;
            GetOldFieldValueMethods[UserObjectPolicyModel.PropertyModel.PolicyRights.PropertyIndex]  = (item) => item.oldPolicyRights;
            GetOldFieldValueMethods[UserObjectPolicyModel.PropertyModel.OrderIndex.PropertyIndex]    = (item) => item.oldOrderIndex;

            SetFieldValueMethods = new Action<UserObjectPolicy, object>[maxIndex + 1];
            SetFieldValueMethods[UserObjectPolicyModel.PropertyModel.Id.PropertyIndex]            = (item, value) => item.id = (long)value;
            SetFieldValueMethods[UserObjectPolicyModel.PropertyModel.PreviousId.PropertyIndex]    = (item, value) => item.previousId = (long)value;
            SetFieldValueMethods[UserObjectPolicyModel.PropertyModel.UserId.PropertyIndex]        = (item, value) => item.userId = (long)value;
            SetFieldValueMethods[UserObjectPolicyModel.PropertyModel.ObjectTableId.PropertyIndex] = (item, value) => item.objectTableId = (int)value;
            SetFieldValueMethods[UserObjectPolicyModel.PropertyModel.ObjectId.PropertyIndex]      = (item, value) => item.objectId = (long)value;
            SetFieldValueMethods[UserObjectPolicyModel.PropertyModel.PolicyRights.PropertyIndex]  = (item, value) => item.policyRights = (UserPolicyRights)value;
            SetFieldValueMethods[UserObjectPolicyModel.PropertyModel.OrderIndex.PropertyIndex]    = (item, value) => item.orderIndex = (int)value;

            SetOldFieldValueMethods = new Action<UserObjectPolicy, object>[maxIndex + 1];
            SetOldFieldValueMethods[UserObjectPolicyModel.PropertyModel.Id.PropertyIndex]            = (item, value) => item.oldId = (long)value;
            SetOldFieldValueMethods[UserObjectPolicyModel.PropertyModel.PreviousId.PropertyIndex]    = (item, value) => item.oldPreviousId = (long)value;
            SetOldFieldValueMethods[UserObjectPolicyModel.PropertyModel.UserId.PropertyIndex]        = (item, value) => item.oldUserId = (long)value;
            SetOldFieldValueMethods[UserObjectPolicyModel.PropertyModel.ObjectTableId.PropertyIndex] = (item, value) => item.oldObjectTableId = (int)value;
            SetOldFieldValueMethods[UserObjectPolicyModel.PropertyModel.ObjectId.PropertyIndex]      = (item, value) => item.oldObjectId = (long)value;
            SetOldFieldValueMethods[UserObjectPolicyModel.PropertyModel.PolicyRights.PropertyIndex]  = (item, value) => item.oldPolicyRights = (UserPolicyRights)value;
            SetOldFieldValueMethods[UserObjectPolicyModel.PropertyModel.OrderIndex.PropertyIndex]    = (item, value) => item.oldOrderIndex = (int)value;
        }

        #endregion |   Static Methods Initialization   |

        #region |   Properties by Object Property Model   |

        /// <summary>
        /// Gets or sets UserId
        /// </summary>
        public long UserId
        {
            get { return this.userId; }
            set { this.SetPropertyValue(UserObjectPolicyModel.PropertyModel.UserId, value); }
		}

        /// <summary>
        /// Gets or sets ObjectTableId
        /// </summary>
        public int ObjectTableId
        {
            get { return this.objectTableId; }
            set { this.SetPropertyValue(UserObjectPolicyModel.PropertyModel.ObjectTableId, value); }
		}

        /// <summary>
        /// Gets or sets ObjectId
        /// </summary>
        public long ObjectId
        {
            get { return this.objectId; }
            set { this.SetPropertyValue(UserObjectPolicyModel.PropertyModel.ObjectId, value); }
		}

        /// <summary>
        /// Gets or sets PolicyRights
        /// </summary>
        public UserPolicyRights PolicyRights
        {
            get { return this.policyRights; }
            set { this.SetPropertyValue(UserObjectPolicyModel.PropertyModel.PolicyRights, value); }
		}

        #endregion |   Properties by Object Property Model   |

        #region |   One-To-Many Relation Properties   |

        /// <summary>
        /// Gets or sets one-to-many relation primary User object.
        /// </summary>
        public User User
        {
            get { return this.GetOneToManyPrimaryObject<User>(RelationPolicyModel.OneToManyUserObjectPolicyToUser)!; }
            set { this.SetOneToManyPrimaryObject(value, RelationPolicyModel.OneToManyUserObjectPolicyToUser); }
        }

        /// <summary>
        /// Gets one-to-many relation foreign GraphElements collection.
        /// </summary>
        public override SimpleObjectCollection<GraphElement> GraphElements
        {
            get { return this.GetOneToManyForeignObjectCollection<GraphElement>(RelationPolicyModelBase.OneToManyGraphElementToSimpleObject); }
        }

        #endregion |   One-To-Many Relation Properties   |

        #region |   Public Overriden Methods   |

        /// <summary>
        /// Gets the UserObjectPolicyModel definition instance.
        /// </summary>
        public override ISimpleObjectModel GetModel()
        {
            return UserObjectPolicyModel.Instance; 
        }

        /// <summary>
        /// Gets the one-to-many collection based on relation key. If no one-to-many relation specified in relation model for this object, the base class method is called.
        /// </summary>
        /// <param name="relationKey">The one-to-many relation key</param>
        /// <returns>The <see cref="SimpleObjectCollection?"/> result.</returns>
        public override SimpleObjectCollection? GetOneToManyForeignObjectCollection(int relationKey)
        {
            if (relationKey == RelationPolicyModelBase.OneToManyGraphElementToSimpleObject.RelationKey)
                return this.GraphElements;

            return base.GetOneToManyForeignObjectCollection(relationKey);
        }

        #endregion |   Public Overriden Methods   |

        #region |   Protected Abstract Overriden Methods  |

        /// <summary>
        /// Gets field property value by property index.
        /// </summary>
        protected override object? GetFieldValue(int propertyIndex)
        {
            return GetFieldValueMethods[propertyIndex](this);
        }

        /// <summary>
        /// Gets field old property value by property index.
        /// </summary>
        protected override object? GetOldFieldValue(int propertyIndex)
        {
            return GetOldFieldValueMethods[propertyIndex](this);
        }

        /// <summary>
        /// Sets field property value by property index.
        /// </summary>
        protected override void SetFieldValue(int propertyIndex, object value)
        {
            SetFieldValueMethods[propertyIndex](this, value);
        }

        /// <summary>
        /// Sets field old property value by property index.
        /// </summary>
        protected override void SetOldFieldValue(int propertyIndex, object value)
        {
            SetOldFieldValueMethods[propertyIndex](this, value);
        }

        #endregion |   Protected Abstract Overriden Methods  |
    }

    #endregion |   Code Generated by Simple.Objects Code Generator   |
}
